### PR TITLE
add lights.msm8953 support

### PR DESCRIPTION
**Pull request by Tofee**
Change-Id: I3fbac77d46c8e23fa4ef4d3bfee1e8f7c8cc883b
Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>

### CODE REVIEW

**Comment by Herrie82** [comment]
@Tofee Seems like we might need something like this as well? https://github.com/Tissot-Development/android_device_xiaomi_tissot/commit/cef44d45904f0ae3e304a7492c0795caee72a174

Not sure about this one, but seems to make sense as well?
https://github.com/Tissot-Development/android_device_xiaomi_tissot/blob/71b4b4f91398fce1c89edc151e237f9c5b874fde/BoardConfig.mk#L165

**Comment by Tofee** [comment]
For the latter remark, I agree it would make sense to add this little flag.

However for the former, the commit concerns a completely different code than what I've committed, so it's won't be useful in this case.

**Comment by Tofee** [comment]
And it seems we actually already have that second flag: https://github.com/Herrie82/android_device_xiaomi_tissot/blob/cm-14.1/BoardConfig.mk#L163

**Comment by Herrie82** [comment]
@tofee Question I guess remains which liblight code is "better" ?

**Comment by Tofee** [comment]
I have no idea. Let's try this one first?

**Comment by Herrie82** [comment]
@Tofee Good idea :P Merged :)

**Pull request merged**
